### ISSUE TITLE
Uncaught TypeError: $(...).chosen is not a function 

### ISSUE THREAD

**Issue by piotr-dobrogost** [j23d/kotti_settings#4]
Trying out version 0.5 of kotti_navigation with version 0.2 of kotti_settings I get below error in js console on line 248 when visiting @@settings view.
Line 248 is `$('.i-can-haz-chzn-select').chosen();`.

```
Uncaught TypeError: $(...).chosen is not a function
(anonymous function) @ @@settings:248
fire @ jquery.js:1037
self.fireWith @ jquery.js:1148
jQuery.extend.ready @ jquery.js:433
completed @ jquery.js:103
```

Btw, `i-can-haz-chzn-select` class is present in deform_bootstrap package however you removed dependency on this package in commit c4449d61f06f8376a12e3c83086bb2a87d12f170 Do you depend on deform_bootstrap?

**Comment by j23d** [comment]
Yes, you are right. deform_bootstrap needs to be a requirement. Thanks for investigation.
